{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
{{- if .Values.certmanager.enable }}
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
{{- else }}
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
{{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
