---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - external-dns.webhippie.de
  resources:
  - dnswatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-dns.webhippie.de
  resources:
  - dnswatchers/finalizers
  verbs:
  - update
- apiGroups:
  - external-dns.webhippie.de
  resources:
  - dnswatchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
