{{- if .Values.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - externaldns.k8s.io
    resources:
      - dnsendpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  {{- if .Values.rbac.extraRules }}
  {{- toYaml .Values.rbac.extraRules | nindent 2 }}
  {{- end }}
{{- end -}}
