---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: helmdocs

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  helmdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write"}

      - name: Checkout source
        uses: actions/checkout@v5
        with:
          token: ${{ steps.token.outputs.token }}
          fetch-depth: 0

      - name: Update readme
        uses: docker://jnorwood/helm-docs:v1.14.2
        with:
          entrypoint: helm-docs

      - name: Source rebase
        run: git pull --autostash --rebase

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: chart/
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...
